// DO NOT EDIT THIS FILE. IT IS ONLY USED FOR BUILDING DEPENDENCIES IN DOCKER
use dioxus::prelude::*;
use api::TEST;
fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        h1 {
            "Build"
            {TEST.to_string()}
        }
    }
}